kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-ssd
  annotations:
    volume.beta.kubernetes.io/storage-class: local-ssd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
